# This is a basic workflow to help you get started with Actions

name: Deploy Release Candidate

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        if: github.ref == 'refs/heads/release'
      - uses: actions/checkout@v2
      - run: |
          git config user.name $GITHUB_ACTOR
          git config user.email gh-actions-${GITHUB_ACTOR}@github.com
      - uses: actions/setup-node@v1
      - run: npm ci
      - run: npx semantic-release
      - run: git checkout develop && git merge release  
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
