name: Publish Latest Release

on:
  workflow_dispatch:

jobs:
  build:
    name: Publish Official Release
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Release
        uses: actions/checkout@v2.3.4
        with:
          ref: master
          token: ${{ secrets.ADMIN_GH_TOKEN }}

      - name: Git Configs, Checkout Master & Merge Release
        run: |
          git config user.name $GITHUB_ACTOR
          git config user.email gh-actions-${GITHUB_ACTOR}@github.com
          git fetch
          git checkout release
          git checkout master
          git merge --ff-only release

      - uses: actions/setup-node@v1

      - name: Run semantic release
        run: |
          npm ci
          npx semantic-release
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Merge/Push back to develop & release
        run: |
          git checkout develop
          git merge --ff-only master
          git push origin develop
          git checkout release
          git merge --ff-only master
          git push origin release
