name: Release Candidate

on:
  workflow_dispatch:

jobs:
  build:
    name: Version & Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Release
        uses: actions/checkout@v2.3.4
        with:
          ref: release
          # token: ''

      - name: Git Configs, Checkout Release & rebase onto develop
        run: |
          git config user.name $GITHUB_ACTOR
          git config user.email gh-actions-${GITHUB_ACTOR}@github.com
          git config pull.ff only
          git pull origin develop --allow-unrelated-histories

      - uses: actions/setup-node@v1

      - name: Run semantic release
        run: |
          npm ci
          npx semantic-release

      - name: Merge back to develop and push
        run: |
          git checkout develop
          git merge release
          git push origin develop

        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
